#!/usr/bin/env python3
"""Render credential-free Windows/macOS clients for desktop-server.

The renderer accepts deployment facts at invocation time. Nothing private is
committed to this public repository, and no private key or RDP password enters
the generated bundle.
"""

from __future__ import annotations

import argparse
import base64
import os
import pathlib
import re
import shutil
import stat
import tempfile


HOST_RE = re.compile(r"(?:[A-Za-z0-9](?:[A-Za-z0-9.-]{0,251}[A-Za-z0-9])?|(?:\d{1,3}\.){3}\d{1,3})")
USER_RE = re.compile(r"[A-Za-z_][A-Za-z0-9_.-]{0,31}")


def checked_host(value: str) -> str:
    if not HOST_RE.fullmatch(value) or ".." in value or value.startswith("-"):
        raise argparse.ArgumentTypeError("host must be a DNS name or IPv4 address")
    return value


def checked_user(value: str) -> str:
    if not USER_RE.fullmatch(value) or value.startswith("-"):
        raise argparse.ArgumentTypeError("user contains unsupported characters")
    return value


def checked_port(value: str) -> int:
    port = int(value)
    if not 1 <= port <= 65535:
        raise argparse.ArgumentTypeError("port must be between 1 and 65535")
    return port


def public_key(path: pathlib.Path) -> tuple[str, str]:
    if path.is_symlink() or not path.is_file():
        raise ValueError("host key file must be a regular file")
    fields = path.read_text(encoding="utf-8").strip().split()
    if len(fields) not in (2, 3) or fields[0] != "ssh-ed25519":
        raise ValueError("host key must contain exactly one ssh-ed25519 public key")
    try:
        decoded = base64.b64decode(fields[1], validate=True)
    except ValueError as exc:
        raise ValueError("host key is not valid base64") from exc
    # SSH wire form: 4-byte length, "ssh-ed25519", 4-byte length, 32-byte key.
    if len(decoded) != 51 or decoded[4:15] != b"ssh-ed25519" or decoded[-36:-32] != b"\x00\x00\x00\x20":
        raise ValueError("host key is not a 32-byte Ed25519 SSH key")
    return fields[0], fields[1]


def rdp_profile(local_port: int, desktop_user: str, slow: bool) -> str:
    values = {
        "full address:s": f"127.0.0.1:{local_port}",
        "username:s": desktop_user,
        "screen mode id:i": "2",
        "desktopwidth:i": "1920",
        "desktopheight:i": "1080",
        "session bpp:i": "32",
        "use multimon:i": "0",
        "dynamic resolution:i": "0",
        "smart sizing:i": "1",
        "prompt for credentials:i": "1",
        "authentication level:i": "2",
        "connection type:i": "2" if slow else "5",
        "networkautodetect:i": "0",
        "bandwidthautodetect:i": "0",
        "compression:i": "1",
        "autoreconnection enabled:i": "1",
        "redirectclipboard:i": "1",
        "redirectprinters:i": "0",
        "audiomode:i": "2" if slow else "0",
        "audiocapturemode:i": "0",
        "disable wallpaper:i": "1",
        "disable full window drag:i": "1",
        "disable menu anims:i": "1",
        "allow font smoothing:i": "1",
    }
    return "".join(f"{key}:{value}\n" for key, value in values.items())


def macos_installer(name: str, host: str, ssh_user: str, key_type: str, key: str,
                    ssh_ports: list[int], local_port: int) -> str:
    ports = " ".join(str(port) for port in ssh_ports)
    return f'''#!/bin/bash
# Generated by macos-ubuntu-bootstrap. Contains no credentials.
set -Eeuo pipefail
label=com.nddev.desktop-server.rdp-tunnel
alias_name=nddev-desktop-server-tunnel
name={name!r}
host={host!r}
ssh_user={ssh_user!r}
local_port={local_port}
ports={ports!r}

main() {{
  [[ $(uname -s) == Darwin && $EUID -ne 0 ]] || {{ echo "Run as the logged-in macOS user." >&2; return 1; }}
  local key_file=${{1:-"$HOME/.ssh/id_ed25519"}}
  local base="$HOME/Library/Application Support/NDDev/DesktopServer"
  local agent="$HOME/Library/LaunchAgents/$label.plist"
  local target="gui/$(id -u)/$label" stage escaped_base
  [[ -r $key_file ]] || {{ echo "SSH key not readable: $key_file" >&2; return 1; }}
  key_file="$(cd "$(dirname "$key_file")" && pwd -P)/$(basename "$key_file")"
  case "$base$key_file" in *$'\\n'*|*$'\\r'*|*'"'*|*\\\\*|*'%'*) echo 'Unsupported path character.' >&2; return 1;; esac
  umask 077
  stage=$(mktemp -d "${{TMPDIR:-/tmp}}/nddev-desktop-server.XXXXXX")
  trap 'rm -rf -- "$stage"' EXIT
  printf '%s %s %s\\n' "$host" {key_type!r} {key!r} >"$stage/known_hosts"
  cat >"$stage/ssh_config" <<EOF
Host $alias_name
    HostName $host
    HostKeyAlias $host
    User $ssh_user
    IdentityFile "$key_file"
    IdentitiesOnly yes
    IdentityAgent none
    BatchMode yes
    PreferredAuthentications publickey
    PasswordAuthentication no
    KbdInteractiveAuthentication no
    ForwardAgent no
    UserKnownHostsFile "$base/known_hosts"
    GlobalKnownHostsFile /dev/null
    StrictHostKeyChecking yes
    UpdateHostKeys no
    ConnectTimeout 10
    ConnectionAttempts 1
    ServerAliveInterval 15
    ServerAliveCountMax 3
    ExitOnForwardFailure yes
    ControlMaster no
    LocalForward 127.0.0.1:$local_port 127.0.0.1:3389
EOF
  cat >"$stage/tunnel.sh" <<'EOF'
#!/bin/bash
set -eu
config=$1; log=$2; ports=$3
while :; do
  for port in $ports; do
    /usr/bin/ssh -NT -p "$port" -F "$config" -E "$log" nddev-desktop-server-tunnel || true
    /bin/sleep 5
  done
done
EOF
  escaped_base=$(printf '%s' "$base" | sed -e 's/&/\\&amp;/g' -e 's/</\\&lt;/g' -e 's/>/\\&gt;/g')
  cat >"$stage/agent.plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
<key>Label</key><string>$label</string><key>ProgramArguments</key><array>
<string>/bin/bash</string><string>$escaped_base/tunnel.sh</string><string>$escaped_base/ssh_config</string>
<string>$escaped_base/tunnel.log</string><string>$ports</string></array>
<key>RunAtLoad</key><true/><key>KeepAlive</key><true/><key>ThrottleInterval</key><integer>10</integer>
<key>StandardOutPath</key><string>/dev/null</string><key>StandardErrorPath</key><string>$escaped_base/tunnel.log</string>
</dict></plist>
EOF
  /usr/bin/plutil -lint "$stage/agent.plist"
  local ssh_ready=0 port
  for port in $ports; do
    if /usr/bin/ssh -p "$port" -F "$stage/ssh_config" \
      -o "UserKnownHostsFile=$stage/known_hosts" -o ClearAllForwardings=yes \
      "$alias_name" true; then
      ssh_ready=1
      break
    fi
  done
  [[ $ssh_ready -eq 1 ]] || {{ echo 'SSH authentication failed on every configured port.' >&2; return 1; }}
  launchctl bootout "$target" 2>/dev/null || true
  mkdir -p "$base" "$(dirname "$agent")" "$HOME/Downloads"
  chmod 700 "$base"
  install -m 600 "$stage/known_hosts" "$base/known_hosts"
  install -m 600 "$stage/ssh_config" "$base/ssh_config"
  install -m 700 "$stage/tunnel.sh" "$base/tunnel.sh"
  install -m 644 "$stage/agent.plist" "$agent"
  cp "$(dirname "$0")/desktop-server.rdp" "$HOME/Downloads/desktop-server.rdp"
  cp "$(dirname "$0")/desktop-server-slow-network.rdp" "$HOME/Downloads/desktop-server-slow-network.rdp"
  launchctl bootstrap "gui/$(id -u)" "$agent"
  for _ in {{1..30}}; do
    /usr/bin/nc -z 127.0.0.1 "$local_port" >/dev/null 2>&1 && break
    /bin/sleep 1
  done
  /usr/bin/nc -z 127.0.0.1 "$local_port" >/dev/null 2>&1 || {{
    echo "Tunnel started, but local RDP port 127.0.0.1:$local_port is not ready; inspect $base/tunnel.log." >&2
    return 1
  }}
  echo "Ready: import desktop-server.rdp into Windows App and connect to 127.0.0.1:$local_port."
}}
main "$@"
'''


def windows_installer(name: str, host: str, ssh_user: str, key_type: str, key: str,
                      ssh_ports: list[int], local_port: int) -> str:
    ports = ", ".join(str(port) for port in ssh_ports)
    # PowerShell's stop-parsing and quoting rules are avoided: every ssh token
    # is a separate ProcessStartInfo.ArgumentList member.
    return f'''# Generated by macos-ubuntu-bootstrap. Contains no credentials.
[CmdletBinding()]
param([string]$IdentityFile = "$HOME\\.ssh\\id_ed25519")
$ErrorActionPreference = "Stop"
if (-not (Get-Command ssh.exe -ErrorAction SilentlyContinue)) {{ throw "Windows OpenSSH Client is required" }}
if (-not (Test-Path -LiteralPath $IdentityFile -PathType Leaf)) {{ throw "SSH key not readable: $IdentityFile" }}
$Base = Join-Path $env:LOCALAPPDATA "NDDev\\DesktopServer"
$Stage = Join-Path ([IO.Path]::GetTempPath()) ("nddev-desktop-server-" + [guid]::NewGuid())
New-Item -ItemType Directory -Path $Stage | Out-Null
try {{
  "{host} {key_type} {key}" | Set-Content -Encoding ascii (Join-Path $Stage "known_hosts")
  @"
Host nddev-desktop-server-tunnel
    HostName {host}
    HostKeyAlias {host}
    User {ssh_user}
    IdentityFile "$IdentityFile"
    IdentitiesOnly yes
    BatchMode yes
    PreferredAuthentications publickey
    PasswordAuthentication no
    KbdInteractiveAuthentication no
    ForwardAgent no
    UserKnownHostsFile "$Base\\known_hosts"
    GlobalKnownHostsFile NUL
    StrictHostKeyChecking yes
    UpdateHostKeys no
    ConnectTimeout 10
    ConnectionAttempts 1
    ServerAliveInterval 15
    ServerAliveCountMax 3
    ExitOnForwardFailure yes
    LocalForward 127.0.0.1:{local_port} 127.0.0.1:3389
"@ | Set-Content -Encoding ascii (Join-Path $Stage "ssh_config")
  @'
$ErrorActionPreference = "Continue"
$Ports = @({ports})
while ($true) {{
  foreach ($Port in $Ports) {{
    & "$env:WINDIR\\System32\\OpenSSH\\ssh.exe" -NT -p $Port -F "$env:LOCALAPPDATA\\NDDev\\DesktopServer\\ssh_config" nddev-desktop-server-tunnel
    Start-Sleep -Seconds 5
  }}
}}
'@ | Set-Content -Encoding utf8 (Join-Path $Stage "tunnel.ps1")
  $SshReady = $false
  foreach ($Port in @({ports})) {{
    & ssh.exe -p $Port -F (Join-Path $Stage "ssh_config") -o ("UserKnownHostsFile=" + (Join-Path $Stage "known_hosts")) -o ClearAllForwardings=yes nddev-desktop-server-tunnel true
    if ($LASTEXITCODE -eq 0) {{ $SshReady = $true; break }}
  }}
  if (-not $SshReady) {{ throw "SSH authentication failed on every configured port" }}
  New-Item -ItemType Directory -Force -Path $Base | Out-Null
  Copy-Item -Force (Join-Path $Stage "known_hosts") (Join-Path $Base "known_hosts")
  Copy-Item -Force (Join-Path $Stage "ssh_config") (Join-Path $Base "ssh_config")
  Copy-Item -Force (Join-Path $Stage "tunnel.ps1") (Join-Path $Base "tunnel.ps1")
  Copy-Item -Force (Join-Path $PSScriptRoot "desktop-server.rdp") (Join-Path ([Environment]::GetFolderPath("MyDocuments")) "desktop-server.rdp")
  Copy-Item -Force (Join-Path $PSScriptRoot "desktop-server-slow-network.rdp") (Join-Path ([Environment]::GetFolderPath("MyDocuments")) "desktop-server-slow-network.rdp")
  $Action = New-ScheduledTaskAction -Execute "powershell.exe" -Argument ('-NoProfile -NonInteractive -WindowStyle Hidden -ExecutionPolicy RemoteSigned -File "' + (Join-Path $Base "tunnel.ps1") + '"')
  $Trigger = New-ScheduledTaskTrigger -AtLogOn -User $env:USERNAME
  $Settings = New-ScheduledTaskSettingsSet -RestartCount 999 -RestartInterval (New-TimeSpan -Minutes 1) -ExecutionTimeLimit ([TimeSpan]::Zero)
  Register-ScheduledTask -TaskName "NDDev Desktop Server RDP Tunnel" -Action $Action -Trigger $Trigger -Settings $Settings -Description "Loopback-only RDP over pinned OpenSSH" -Force | Out-Null
  Start-ScheduledTask -TaskName "NDDev Desktop Server RDP Tunnel"
  $RdpReady = $false
  for ($Attempt = 0; $Attempt -lt 30; $Attempt++) {{
    if ((Test-NetConnection -ComputerName 127.0.0.1 -Port {local_port} -InformationLevel Quiet -WarningAction SilentlyContinue)) {{ $RdpReady = $true; break }}
    Start-Sleep -Seconds 1
  }}
  if (-not $RdpReady) {{ throw "Tunnel started, but local RDP port 127.0.0.1:{local_port} is not ready" }}
  Write-Host "Ready: open Documents\\desktop-server.rdp with Windows App or Remote Desktop Connection."
}} finally {{ Remove-Item -LiteralPath $Stage -Recurse -Force -ErrorAction SilentlyContinue }}
'''


def write(path: pathlib.Path, payload: str, mode: int) -> None:
    path.write_text(payload, encoding="utf-8", newline="\n")
    path.chmod(mode)


def render(args: argparse.Namespace) -> None:
    key_type, key = public_key(args.host_key_file)
    out = args.out.resolve()
    if out.exists():
        raise ValueError(f"output already exists; preserved: {out}")
    out.parent.mkdir(parents=True, exist_ok=True)
    stage = pathlib.Path(tempfile.mkdtemp(prefix=f".{out.name}.", dir=out.parent))
    try:
        write(stage / "desktop-server.rdp", rdp_profile(args.local_port, args.desktop_user, False), 0o644)
        write(stage / "desktop-server-slow-network.rdp", rdp_profile(args.local_port, args.desktop_user, True), 0o644)
        write(stage / "install-macos-tunnel.sh", macos_installer(
            args.name, args.host, args.ssh_user, key_type, key, args.ssh_ports, args.local_port), 0o755)
        write(stage / "install-windows-tunnel.ps1", windows_installer(
            args.name, args.host, args.ssh_user, key_type, key, args.ssh_ports, args.local_port), 0o644)
        write(stage / "README.txt", f"""{args.name}\n\nServer: {args.host}\nRDP endpoint after tunnel install: 127.0.0.1:{args.local_port}\nDesktop user: {args.desktop_user}\n\nThe bundle contains no password or private key. Run the installer for the client OS, then import the normal or slow-network RDP profile.\n""", 0o644)
        os.replace(stage, out)
    except BaseException:
        shutil.rmtree(stage, ignore_errors=True)
        raise


def parser() -> argparse.ArgumentParser:
    result = argparse.ArgumentParser(description=__doc__)
    result.add_argument("--host", required=True, type=checked_host)
    result.add_argument("--ssh-user", required=True, type=checked_user)
    result.add_argument("--desktop-user", required=True, type=checked_user)
    result.add_argument("--host-key-file", required=True, type=pathlib.Path)
    result.add_argument("--ssh-port", dest="ssh_ports", action="append", type=checked_port)
    result.add_argument("--local-port", type=checked_port, default=13389)
    result.add_argument("--name", default="Ubuntu Desktop Server")
    result.add_argument("--out", required=True, type=pathlib.Path)
    return result


def main() -> None:
    args = parser().parse_args()
    args.ssh_ports = args.ssh_ports or [22, 443]
    if len(args.ssh_ports) != len(set(args.ssh_ports)):
        raise SystemExit("SSH ports must be unique")
    try:
        render(args)
    except (OSError, ValueError) as exc:
        raise SystemExit(str(exc)) from exc


if __name__ == "__main__":
    main()
